### ISSUE TITLE
Problem trying to run the app in Android Studio

### ISSUE THREAD

**Issue by CountDookie** [mang0055/DoorsOpenOttawa#1]
Hello Raviraj,

I am currently a student from Algonquin Colllege and is developing a mobile app for my Co-op term, I was referred to your app's github page for learning by Mr.Adesh Nilesh Shah. I want to post this issue to request help as I have trouble running the source code on Android Studio version 4.1.2. The problem is that the Gradle version used for this app is not supported by the IDE so one method is not used. I have attached 2 screenshots here and I hope that this will suffice. Please let me know if you have any idea or it would be great if you can tell me how you would normally run the app. 

Thank you for reading this,

Bach Le

![image](https://user-images.githubusercontent.com/43048825/105865876-efe8cd00-6025-11eb-8225-e7d895109bde.png)
![image](https://user-images.githubusercontent.com/43048825/105865941-01ca7000-6026-11eb-9648-0c3a3991a5a6.png)

**Comment by ravirajcm** [comment]
Fixed it in 
https://github.com/ravirajcm/DoorsOpenOttawa/commit/18fad59d88496f87a52d78ab9189655741f713f3
